name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: ./gradlew build

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 43.201.36.106
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "~/spring-app"

      - name: Run Spring Boot app on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 43.201.36.106
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "pkill -f 'java -jar' || true" | at now
            echo "cd ~/spring-app && nohup java -jar ./build/libs/SWTTProject-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &" | at now